"""cenplex model extensions

Revision ID: 1d06494aed80
Revises: 1a8ce1447621
Create Date: 2026-03-26 08:57:36.450538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d06494aed80'
down_revision = '1a8ce1447621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_settings', schema=None) as batch_op:
        batch_op.alter_column('budget_monthly',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('budget_used',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_on_waitlist', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_remote', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_virtual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mtt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_pauschal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pauschal_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_emr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_ergo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_billable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bill_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cost_unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('additional_employees_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('effort_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('booking_messages_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_history_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sum_of_positions', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('public_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('was_booked_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by_patient', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('booker_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('web_booker_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('was_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_printed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_mailed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_sms_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_triggered', sa.Boolean(), nullable=True))
        batch_op.alter_column('cancellation_fee',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'contacts', ['cost_unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['soap_updated_by_id'], ['id'])

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=34),
               type_=utils.encryption.EncryptedString(),
               existing_nullable=False)
        batch_op.alter_column('qr_iban',
               existing_type=sa.VARCHAR(length=34),
               type_=utils.encryption.EncryptedString(),
               existing_nullable=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gln_receiver', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('postbox', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('affiliate_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('law_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expertise', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('supports_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accept_kostengutsprache', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_gutsprache', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tarif_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('addressing', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_imported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reference_contact_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contacts', ['reference_contact_id'], ['id'])

    with op.batch_alter_table('cost_approval_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('cost_approvals', schema=None) as batch_op:
        batch_op.alter_column('approved_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('creditor_invoices', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('vat_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('dunning_records', schema=None) as batch_op:
        batch_op.alter_column('dunning_fee',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('employee_children', schema=None) as batch_op:
        batch_op.alter_column('allowance_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('employee_salaries', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('hourly_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('bvg_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('nbuv_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('ktg_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('internal_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ahv_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('asca_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emr_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('temp_gln', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_rights_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_groups_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('app_settings_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calendar_default_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('send_invoice_as_practice', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('booking_sync_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('booking_sync_till', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('booking_book_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('vat_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.alter_column('acquisition_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('current_book_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxpoint_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('unit_price_netto', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valuta_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_credit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_points',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_point_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('vat_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('vat_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_case', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('cost_unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sent_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('was_disapproved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('apply_vat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_vat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exclude_discount', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('medidata_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medidata_state_changed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('transmission_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_xml45', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('closed_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('print_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_send_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('amount_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount_paid',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount_open',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_point_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'contacts', ['cost_unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['approved_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['sent_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'bank_accounts', ['bank_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.alter_column('debit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('credit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('vat_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kanton', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('is_kvg_base', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kvg_model', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kvg_accident_coverage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('card_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('card_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('costunit_uvg_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('costunit_vvg_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('insured_id_vvg', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('card_id_vvg', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('card_vvg_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('insurance_extra_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_firstname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_lastname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_company', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_zipcode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_town', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_kanton', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('premium_payer_country', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('egym_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vald_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dividat_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mywellness_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referenced_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('deposit_payed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deposit_receipt_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deposit_payed_back_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.alter_column('insurance_number',
               existing_type=sa.VARCHAR(length=30),
               type_=utils.encryption.EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('ahv_number',
               existing_type=sa.VARCHAR(length=16),
               type_=utils.encryption.EncryptedString(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(None, 'contacts', ['referenced_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'contacts', ['costunit_uvg_id'], ['id'])
        batch_op.create_foreign_key(None, 'contacts', ['costunit_vvg_id'], ['id'])
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reduction_reason', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_fully_payed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payed_too_much', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_from_file', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_inkasso', sa.Boolean(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.alter_column('total_gross',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_net',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_employer_contributions',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('gross_salary',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('thirteenth_month',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('child_allowance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('bonuses',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('expenses_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('overtime_payout',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('gross_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('ahv_iv_eo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('alv',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('alv2',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('bvg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('nbuv',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('ktg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('withholding_tax',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('deductions_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('net_salary',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_ahv_iv_eo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_alv',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_bvg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_uvg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_ktg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_fak',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_vk',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('employer_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('product_price_history', schema=None) as batch_op:
        batch_op.alter_column('old_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('new_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('net_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('vat_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('subscription_templates', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('tax_point_values', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treatment_series', schema=None) as batch_op:
        batch_op.alter_column('diagnosis_code',
               existing_type=sa.VARCHAR(length=20),
               type_=utils.encryption.EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('diagnosis_text',
               existing_type=sa.VARCHAR(length=500),
               type_=utils.encryption.EncryptedString(),
               existing_nullable=True)

    with op.batch_alter_table('treatment_series_templates', schema=None) as batch_op:
        batch_op.alter_column('cancellation_fee_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_series_templates', schema=None) as batch_op:
        batch_op.alter_column('cancellation_fee_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('treatment_series', schema=None) as batch_op:
        batch_op.alter_column('diagnosis_text',
               existing_type=utils.encryption.EncryptedString(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('diagnosis_code',
               existing_type=utils.encryption.EncryptedString(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('tax_point_values', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('subscription_templates', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('vat_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('net_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('product_price_history', schema=None) as batch_op:
        batch_op.alter_column('new_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('old_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('employer_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('employer_vk',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('employer_fak',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('employer_ktg',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('employer_uvg',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('employer_bvg',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('employer_alv',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('employer_ahv_iv_eo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('net_salary',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('deductions_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('withholding_tax',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('ktg',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('nbuv',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('bvg',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('alv2',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('alv',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('ahv_iv_eo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('gross_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('overtime_payout',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('expenses_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('bonuses',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('child_allowance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('thirteenth_month',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('gross_salary',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.alter_column('total_employer_contributions',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_net',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_gross',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('is_inkasso')
        batch_op.drop_column('is_from_file')
        batch_op.drop_column('payed_too_much')
        batch_op.drop_column('is_fully_payed')
        batch_op.drop_column('reduction_reason')
        batch_op.drop_column('payment_type')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ahv_number',
               existing_type=utils.encryption.EncryptedString(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('insurance_number',
               existing_type=utils.encryption.EncryptedString(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('location_id')
        batch_op.drop_column('deposit_payed_back_date')
        batch_op.drop_column('deposit_receipt_date')
        batch_op.drop_column('deposit_payed_date')
        batch_op.drop_column('deposit_amount')
        batch_op.drop_column('referenced_by_id')
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('profession')
        batch_op.drop_column('hobbies')
        batch_op.drop_column('mywellness_id')
        batch_op.drop_column('dividat_id')
        batch_op.drop_column('vald_id')
        batch_op.drop_column('egym_id')
        batch_op.drop_column('premium_payer_country')
        batch_op.drop_column('premium_payer_kanton')
        batch_op.drop_column('premium_payer_town')
        batch_op.drop_column('premium_payer_zipcode')
        batch_op.drop_column('premium_payer_address')
        batch_op.drop_column('premium_payer_company')
        batch_op.drop_column('premium_payer_lastname')
        batch_op.drop_column('premium_payer_firstname')
        batch_op.drop_column('insurance_extra_data')
        batch_op.drop_column('card_vvg_expiry')
        batch_op.drop_column('card_id_vvg')
        batch_op.drop_column('insured_id_vvg')
        batch_op.drop_column('costunit_vvg_id')
        batch_op.drop_column('costunit_uvg_id')
        batch_op.drop_column('card_expiry')
        batch_op.drop_column('card_id')
        batch_op.drop_column('kvg_accident_coverage')
        batch_op.drop_column('kvg_model')
        batch_op.drop_column('is_kvg_base')
        batch_op.drop_column('kanton')

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.alter_column('vat_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tax_point_value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_open',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_paid',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('email_send_date')
        batch_op.drop_column('print_date')
        batch_op.drop_column('closed_date')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_xml45')
        batch_op.drop_column('transmission_reference')
        batch_op.drop_column('medidata_state_changed')
        batch_op.drop_column('medidata_state')
        batch_op.drop_column('exclude_discount')
        batch_op.drop_column('include_vat')
        batch_op.drop_column('apply_vat')
        batch_op.drop_column('was_disapproved')
        batch_op.drop_column('sent_by_id')
        batch_op.drop_column('approved_date')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('bank_account_id')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('cost_unit_id')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('billing_case')
        batch_op.drop_column('invoice_type')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('vat_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('vat_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('tax_point_value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('tax_points',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('remark')
        batch_op.drop_column('is_credit')
        batch_op.drop_column('valuta_date')
        batch_op.drop_column('unit_price_netto')
        batch_op.drop_column('taxpoint_code')

    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.alter_column('current_book_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('acquisition_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('vat_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('booking_book_active')
        batch_op.drop_column('booking_sync_till')
        batch_op.drop_column('booking_sync_from')
        batch_op.drop_column('send_invoice_as_practice')
        batch_op.drop_column('calendar_default_interval')
        batch_op.drop_column('app_settings_json')
        batch_op.drop_column('user_groups_json')
        batch_op.drop_column('user_rights_json')
        batch_op.drop_column('temp_gln')
        batch_op.drop_column('emr_number')
        batch_op.drop_column('asca_number')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('ahv_number')
        batch_op.drop_column('internal_number')
        batch_op.drop_column('degree')

    with op.batch_alter_table('employee_salaries', schema=None) as batch_op:
        batch_op.alter_column('ktg_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('nbuv_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('bvg_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('hourly_rate',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('employee_children', schema=None) as batch_op:
        batch_op.alter_column('allowance_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('dunning_records', schema=None) as batch_op:
        batch_op.alter_column('dunning_fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('creditor_invoices', schema=None) as batch_op:
        batch_op.alter_column('vat_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cost_approvals', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('approved_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('cost_approval_items', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reference_contact_id')
        batch_op.drop_column('is_imported')
        batch_op.drop_column('addressing')
        batch_op.drop_column('tarif_code')
        batch_op.drop_column('email_gutsprache')
        batch_op.drop_column('accept_kostengutsprache')
        batch_op.drop_column('supports_online')
        batch_op.drop_column('expertise')
        batch_op.drop_column('law_code')
        batch_op.drop_column('affiliate_id')
        batch_op.drop_column('postbox')
        batch_op.drop_column('gln_receiver')
        batch_op.drop_column('department')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.alter_column('qr_iban',
               existing_type=utils.encryption.EncryptedString(),
               type_=sa.VARCHAR(length=34),
               existing_nullable=True)
        batch_op.alter_column('iban',
               existing_type=utils.encryption.EncryptedString(),
               type_=sa.VARCHAR(length=34),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cancellation_fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('email_triggered')
        batch_op.drop_column('last_sms_sent')
        batch_op.drop_column('last_mailed')
        batch_op.drop_column('last_printed')
        batch_op.drop_column('was_synced')
        batch_op.drop_column('web_booker_id')
        batch_op.drop_column('booker_id')
        batch_op.drop_column('confirmed_by_patient')
        batch_op.drop_column('was_booked_online')
        batch_op.drop_column('public_notes')
        batch_op.drop_column('sum_of_positions')
        batch_op.drop_column('treatment_history_json')
        batch_op.drop_column('booking_messages_json')
        batch_op.drop_column('effort_notes')
        batch_op.drop_column('additional_employees_json')
        batch_op.drop_column('cancellation_date')
        batch_op.drop_column('cost_unit_id')
        batch_op.drop_column('bill_state')
        batch_op.drop_column('is_billable')
        batch_op.drop_column('is_ergo')
        batch_op.drop_column('is_emr')
        batch_op.drop_column('pauschal_price')
        batch_op.drop_column('is_pauschal')
        batch_op.drop_column('is_mtt')
        batch_op.drop_column('is_virtual')
        batch_op.drop_column('is_remote')
        batch_op.drop_column('is_on_waitlist')

    with op.batch_alter_table('ai_settings', schema=None) as batch_op:
        batch_op.alter_column('budget_used',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('budget_monthly',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
