"""organization_id auf Doctor, InsuranceProvider, ChatMessage, Permission

Revision ID: 495b7876aa86
Revises: 
Create Date: 2026-03-23 23:51:29.816122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495b7876aa86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chat_messages_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_doctors_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('insurance_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_insurance_providers_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_org_invoice_number', ['organization_id', 'invoice_number'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_org_patient_number', ['organization_id', 'patient_number'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_permissions_organization_id', 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_permissions_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('uix_org_patient_number', type_='unique')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('uix_org_invoice_number', type_='unique')

    with op.batch_alter_table('insurance_providers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_insurance_providers_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_doctors_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
