"""updated_at und Indexes auf alle Tabellen

Revision ID: cc5ad08af14e
Revises: 495b7876aa86
Create Date: 2026-03-24 04:57:19.951152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5ad08af14e'
down_revision = '495b7876aa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.create_index('ix_absence_emp_dates', ['employee_id', 'start_date', 'end_date'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_account_org_number', ['organization_id', 'account_number'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_appt_emp_start', ['employee_id', 'start_time'], unique=False)
        batch_op.create_index('ix_appt_loc_start', ['location_id', 'start_time'], unique=False)
        batch_op.create_index('ix_appt_patient', ['patient_id', 'start_time'], unique=False)
        batch_op.create_index('ix_appt_series', ['series_id'], unique=False)
        batch_op.create_index('ix_appt_status', ['status', 'start_time'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_org_entity', ['organization_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_user', ['user_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_user', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('cost_approval_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cost_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_costappr_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('ix_costappr_patient', ['patient_id'], unique=False)

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_email_org_folder', ['organization_id', 'folder'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_emp_org_active', ['organization_id', 'is_active'], unique=False)

    with op.batch_alter_table('fitness_visits', schema=None) as batch_op:
        batch_op.create_index('ix_fitvisit_patient', ['patient_id', 'check_in'], unique=False)
        batch_op.create_index('ix_fitvisit_sub', ['subscription_id', 'check_in'], unique=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_invoice_due', ['due_date', 'status'], unique=False)
        batch_op.create_index('ix_invoice_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('ix_invoice_patient', ['patient_id'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('ix_journal_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('ix_journal_source', ['source', 'source_id'], unique=False)

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_loc_org_active', ['organization_id', 'is_active'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('overtime_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.create_index('ix_patdoc_patient', ['patient_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_patient_name', ['last_name', 'first_name'], unique=False)
        batch_op.create_index('ix_patient_org_active', ['organization_id', 'is_active'], unique=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('period_locks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_perm_org_role', ['organization_id', 'role'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_product_org_active', ['organization_id', 'is_active'], unique=False)

    with op.batch_alter_table('resource_bookings', schema=None) as batch_op:
        batch_op.create_index('ix_resbooking_resource_time', ['resource_id', 'start_time', 'end_time'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_resource_loc', ['location_id'], unique=False)
        batch_op.create_index('ix_resource_org_active', ['organization_id', 'is_active'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_sub_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('ix_sub_patient', ['patient_id'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index('ix_setting_org_category', ['organization_id', 'category'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_task_assigned', ['assigned_to_id', 'status'], unique=False)
        batch_op.create_index('ix_task_org_status', ['organization_id', 'status'], unique=False)

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index('ix_timeentry_emp_date', ['employee_id', 'date'], unique=False)

    with op.batch_alter_table('treatment_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_series_patient', ['patient_id'], unique=False)
        batch_op.create_index('ix_series_status', ['status'], unique=False)
        batch_op.create_index('ix_series_therapist', ['therapist_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_user_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('ix_user_role', ['organization_id', 'role'], unique=False)

    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_emp_day', ['employee_id', 'day_of_week'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_emp_day')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role')
        batch_op.drop_index('ix_user_org_active')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('treatment_series', schema=None) as batch_op:
        batch_op.drop_index('ix_series_therapist')
        batch_op.drop_index('ix_series_status')
        batch_op.drop_index('ix_series_patient')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_timeentry_emp_date')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_task_org_status')
        batch_op.drop_index('ix_task_assigned')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_setting_org_category')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_sub_patient')
        batch_op.drop_index('ix_sub_org_status')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_org_active')
        batch_op.drop_index('ix_resource_loc')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('resource_bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_resbooking_resource_time')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_product_org_active')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_perm_org_role')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('period_locks', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_org_active')
        batch_op.drop_index('ix_patient_name')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_patdoc_patient')

    with op.batch_alter_table('overtime_accounts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_loc_org_active')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_source')
        batch_op.drop_index('ix_journal_org_date')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_patient')
        batch_op.drop_index('ix_invoice_org_status')
        batch_op.drop_index('ix_invoice_due')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('fitness_visits', schema=None) as batch_op:
        batch_op.drop_index('ix_fitvisit_sub')
        batch_op.drop_index('ix_fitvisit_patient')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_emp_org_active')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index('ix_email_org_folder')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cost_approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_costappr_patient')
        batch_op.drop_index('ix_costappr_org_status')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cost_approval_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_user')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user')
        batch_op.drop_index('ix_audit_org_entity')
        batch_op.drop_index('ix_audit_created')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appt_status')
        batch_op.drop_index('ix_appt_series')
        batch_op.drop_index('ix_appt_patient')
        batch_op.drop_index('ix_appt_loc_start')
        batch_op.drop_index('ix_appt_emp_start')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_account_org_number')

    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_index('ix_absence_emp_dates')

    # ### end Alembic commands ###
